# fly.toml app configuration file generated for library-tkonzok on 2023-09-02T11:12:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "library-tkonzok"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
